export const protectedScreens = [
  { name: "assistant", title: "Private assistant" },
  { name: "conversation", title: "Private conversation" },
  { name: "household", title: "Today" },
  { name: "agenda", title: "Calendar" },
  { name: "finances", title: "Money" },
  { name: "grocery-expense", title: "Record grocery expense" },
  { name: "expense-entry", title: "Record expense" },
  { name: "correction-entry", title: "Correct entry" },
  { name: "refund-entry", title: "Record refund" },
  { name: "settlement-entry", title: "Record settlement" },
  { name: "recurring-rules", title: "Recurring expenses" },
  { name: "recurring-entry", title: "Recurring setup" },
  { name: "recurring-approval", title: "Review recurring expense" },
  { name: "recurring-resume-approval", title: "Review resumption" },
  { name: "recurring-state-approval", title: "Review recurring change" },
  { name: "recurring-variable-approval", title: "Review variable bill" },
  { name: "recurring-variable", title: "Variable bill" },
  { name: "recurring-state", title: "Recurring controls" },
  { name: "recurring-rule", title: "Recurring expense" },
  { name: "receipt-uploads", title: "Receipt uploads" },
  { name: "receipt", title: "Receipt" },
  { name: "correction-approval", title: "Review correction" },
  { name: "refund-approval", title: "Review refund" },
  { name: "settlement-approval", title: "Review settlement" },
  { name: "expense-approval", title: "Review expense" },
  { name: "money-event", title: "Financial entry" },
  { name: "chore-transfers", title: "Chore handovers" },
  { name: "routines", title: "Routines" },
  { name: "meal-library", title: "Saved recipes" },
  { name: "recipe-edit", title: "Edit recipe" },
  { name: "recipe-archive", title: "Archive recipe" },
  { name: "recipe-create", title: "New recipe" },
  { name: "recipe-select", title: "Choose recipe" },
  { name: "planned-recipe", title: "Planned meal" },
  { name: "saved-meal", title: "Recipe" },
  { name: "meal-week", title: "Meals" },
  { name: "meal-proposal", title: "Week preview" },
  { name: "meal-ingredients", title: "Review ingredients" },
  { name: "meal-add", title: "Add meal" },
  { name: "meal-replace", title: "Replace meal" },
  { name: "meal-preparation-edit", title: "Edit preparation" },
  { name: "meal-preparation", title: "Meal preparation" },
  { name: "meal-leftovers", title: "Plan leftovers" },
  { name: "meal-move", title: "Move meal" },
  { name: "meal-remove", title: "Remove meal" },
  { name: "checklist", title: "Groceries" },
  { name: "grocery-edit", title: "Grocery" },
  { name: "food-preferences", title: "Food preferences" },
  { name: "notification-preferences", title: "Your notifications" },
  { name: "cooking-preferences", title: "Household cooking" },
  { name: "calendar-sharing", title: "Calendar sharing" },
  { name: "memory", title: "Private memory" },
  { name: "setup", title: "Your setup" },
  { name: "settings", title: "Profile and settings" },
] as const;
