-- Read-only catalog metadata query
select jsonb_build_object(
 'tables_without_rls', coalesce((select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname)) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and c.relkind in ('r','p') and not c.relrowsecurity),'[]'::jsonb),
 'anonymous_definers', coalesce((select jsonb_agg(jsonb_build_object('function',p.oid::regprocedure::text)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.prosecdef and has_schema_privilege('anon',n.oid,'USAGE') and has_function_privilege('anon',p.oid,'EXECUTE')),'[]'::jsonb),
 'no_policy_tables', coalesce((select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'rls',c.relrowsecurity,'anon_select',has_table_privilege('anon',c.oid,'SELECT'),'authenticated_select',has_table_privilege('authenticated',c.oid,'SELECT'),'authenticated_write',has_table_privilege('authenticated',c.oid,'INSERT,UPDATE,DELETE'),'authenticated_schema_usage',has_schema_privilege('authenticated',n.oid,'USAGE'))) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and c.relkind in ('r','p') and c.relrowsecurity and not exists(select 1 from pg_policy pol where pol.polrelid=c.oid)),'[]'::jsonb),
 'privileged_functions', coalesce((select jsonb_agg(jsonb_build_object('function',p.oid::regprocedure::text,'owner',r.rolname,'search_path_set',exists(select 1 from unnest(p.proconfig) cfg where cfg like 'search_path=%'),'has_auth_uid_reference',position('auth.uid()' in pg_get_functiondef(p.oid))>0,'has_member_reference',position('require_household' in pg_get_functiondef(p.oid))>0)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_roles r on r.oid=p.proowner where n.nspname='public' and p.prosecdef and has_function_privilege('authenticated',p.oid,'EXECUTE')),'[]'::jsonb),
 'extensions',coalesce((select jsonb_agg(e.extname) from pg_extension e where e.extname in ('pg_cron','pg_net','pgcrypto')),'[]'::jsonb),
 'cron_relation_present',to_regclass('cron.job') is not null
) as audit;

-- Read-only environment metadata query
select jsonb_build_object(
 'cron_jobs',coalesce((select jsonb_agg(jsonb_build_object('jobid',jobid,'jobname',jobname,'schedule',schedule,'active',active,'nest_command',position('nest_' in command)>0,'network_command',position('http_' in command)>0)) from cron.job),'[]'::jsonb),
 'private_tables_without_rls',coalesce((select jsonb_agg(jsonb_build_object('table',c.relname,'owner',r.rolname,'anon_schema_usage',has_schema_privilege('anon',n.oid,'USAGE'),'authenticated_schema_usage',has_schema_privilege('authenticated',n.oid,'USAGE'),'anon_client_privilege',has_table_privilege('anon',c.oid,'SELECT,INSERT,UPDATE,DELETE'),'authenticated_client_privilege',has_table_privilege('authenticated',c.oid,'SELECT,INSERT,UPDATE,DELETE'))) from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_roles r on r.oid=c.relowner where n.nspname='private' and c.relkind in ('r','p') and not c.relrowsecurity),'[]'::jsonb),
 'public_views',coalesce((select jsonb_agg(jsonb_build_object('view',c.relname,'security_invoker',coalesce('security_invoker=true'=any(c.reloptions),false),'anon_select',has_table_privilege('anon',c.oid,'SELECT'),'authenticated_select',has_table_privilege('authenticated',c.oid,'SELECT'))) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='v'),'[]'::jsonb),
 'auth_provider_counts',coalesce((select jsonb_object_agg(provider,total) from (select provider,count(*) total from auth.identities group by provider) q),'{}'::jsonb)
) as audit;

-- Read-only worker metadata query
select jsonb_build_object('worker_function_privileges',coalesce((select jsonb_agg(jsonb_build_object('name',p.proname,'function',p.oid::regprocedure::text,'security_definer',p.prosecdef,'authenticated_execute',has_function_privilege('authenticated',p.oid,'EXECUTE'),'anon_execute',has_function_privilege('anon',p.oid,'EXECUTE'),'service_role_execute',has_function_privilege('service_role',p.oid,'EXECUTE'))) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.proname in ('nest_maintain_meal_reminders','nest_read_meal_push_checkpoint','nest_save_meal_push_checkpoint','nest_scan_meal_push_deliveries','nest_maintain_grocery_reminders','nest_maintain_recurring_reminders','nest_read_grocery_push_checkpoint','nest_read_recurring_push_checkpoint','nest_save_grocery_push_checkpoint','nest_save_recurring_push_checkpoint','nest_scan_grocery_push_deliveries','nest_scan_recurring_push_deliveries','nest_maintain_chore_reminders','nest_read_chore_push_checkpoint','nest_save_chore_push_checkpoint','nest_scan_chore_push_deliveries','nest_maintain_daily_summaries','nest_read_summary_push_checkpoint','nest_save_summary_push_checkpoint','nest_scan_summary_push_deliveries','nest_maintain_push_deliveries','nest_read_push_checkpoint','nest_save_push_checkpoint','nest_scan_push_deliveries','nest_begin_push_delivery','nest_begin_apns_delivery','nest_finish_apns_send','nest_finish_push_send','nest_finish_push_receipt','nest_claim_push_receipt_polls','nest_retry_push_delivery','nest_due_fixed_jobs','nest_execute_fixed_job','nest_claim_recurring_run','nest_finish_recurring_run')),'[]'::jsonb)) as audit;

