import Foundation

extension SessionModel {
    func clearMealPresentation() {
        cookingProfile = nil
        cookingPending = nil
        cookingNotice = nil
        cookingSaving = false
        cookingSavingGeneration = nil
        cookingReadRequest = nil
        mealSelection = nil
        mealStatus = .idle
        mealNotice = nil
        mealPlacement = nil
        mealPlacementSaving = false
        mealVisibleSlots = MealSlot.allCases
        mealSlotNotice = nil
        mealReplacement = nil
        mealReplacementSaving = false
        mealReplacementSavingGeneration = nil
        recipeCreation = nil
        recipeCreationSaving = false
        recipeCreationSavingGeneration = nil
        recipeCreationNotice = nil
        mealLeftovers = nil
        mealLeftoversSaving = false
        mealLeftoversSavingGeneration = nil
        mealMove = nil
        mealMoveSaving = false
        mealMoveSavingGeneration = nil
        mealRemoval = nil
        mealRemovalSaving = false
        mealLibrary = .idle
        mealLibraryNotice = nil
        savedRecipe = .idle
        savedRecipeRevision = nil
        mealRecipePlacement = nil
        mealRecipePlacementSaving = false
        mealLoadingRequest = nil
        mealPlacementSavingGeneration = nil
        mealRemovalSavingGeneration = nil
        mealLibraryRequest = nil
        savedRecipeRequest = nil
        mealRecipePlacementSavingGeneration = nil
        plannedRecipe = .idle
        plannedRecipeNotice = nil
        plannedRecipeTarget = nil
        plannedRecipeFresh = false
        plannedRecipeRequest = nil
    }
}
